name: Update DB

on:
  [push]
  # schedule:
  #   - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: >
          npm install -g yarn
          && yarn install
      - name: Update DB
        run: yarn update-movies
        env:
          REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
          REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
          REACT_APP_DB_URL: ${{secrets.REACT_APP_DB_URL}}
          REACT_APP_IMDB_API_KEY: ${{secrets.REACT_APP_IMDB_API_KEY}}
          REACT_APP_MSG_SENDER_ID: ${{secrets.REACT_APP_MSG_SENDER_ID}}
          REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
          REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
          REACT_APP_FL_TOKEN: ${{secrets.REACT_APP_FL_TOKEN}}
