name: Update DB

on:
  schedule:
    # - cron: '* 23 * * *'
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Script
        run: echo "It is working"
