name: Update DB

on:
  schedule:
    # - cron: '* 23 * * *'
    - cron: '24 18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: >
          npm install -g yarn
          && yarn install
