name: Update DB

on:
  schedule:
    # - cron: '* 23 * * *'
    - cron: '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: >
          npm install -g yarn
          && yarn install
